[workspace]
resolver = "3"

members = [
  "examples/*",
  "crates/nirvana",
  # "crates/monoio",
  # "crates/monoio-compat",
  # "crates/monoio-macros",
]

[workspace.lints.clippy]
macro_use_imports = "warn"

